title:         Beni Dibatia
description:   The official website of Beni Dibatia
baseurl:       ""
url:           ""

# Build settings
markdown:      kramdown
paginate:      5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
